In [34]:
cities=['delhi','bangalore','chenni']
print(cities)

['delhi', 'bangalore', 'chenni']


In [1]:
!pip install modin[ray]

  Created wheel for gpustat: filename=gpustat-0.6.0-cp37-none-any.whl size=12627 sha256=8eb8e4e90834896944301158f66e1ed4338fe746507e1e1ae4dad6240443989b
  Stored in directory: C:\Users\Admin\AppData\Local\pip\Cache\wheels\48\b4\d5\fb5b7f1d040f2ff20687e3bad6867d63155dbde5a7c10f4293
  Created wheel for nvidia-ml-py3: filename=nvidia_ml_py3-7.352.0-cp37-none-any.whl size=19197 sha256=363e59726caa447c33766c52961136183282a0021148f74aa4c9a9584924b89f
  Stored in directory: C:\Users\Admin\AppData\Local\pip\Cache\wheels\e4\1d\06\640c93f5270d67d0247f30be91f232700d19023f9e66d735c7
Successfully built gpustat nvidia-ml-py3
  Found existing installation: pandas 0.24.2
    Uninstalling pandas-0.24.2:
      Successfully uninstalled pandas-0.24.2
  Found existing installation: msgpack 0.6.1
    Uninstalling msgpack-0.6.1:
      Successfully uninstalled msgpack-0.6.1


ERROR: google-api-core 1.25.0 has requirement six>=1.13.0, but you'll have six 1.12.0 which is incompatible.


In [ ]:
###''code will use for singel word
###" " double code will use for singel sentences
###""" """ trile code for paragraph and mutilpe sentences

In [5]:
print('hello')
print("hello bangalore")
print('''hello bangalore "it's bangalore"''')

hello
hello bangalore
hello bangalore "it's bangalore"


In [23]:
d=cities.remove('bangalore')
d

In [24]:
cities

['delhi', 'chenni']

In [29]:
 del cities[0]

In [30]:
cities

['chenni']

In [31]:
dic={"a":"chaitanya","b":"reddy","a":"palle"}##key must be unique value.otherwise the value should be over write
dic

{'a': 'palle', 'b': 'reddy'}

In [38]:
"mumbai" in cities

False

In [39]:
"bangalore" in cities

True

In [40]:
"hydrabd" not in cities

True

In [36]:
len(cities)

3

In [56]:
for i in range(1,10):########inverse of numbers
    print("Inverse of {0} is {1}".format(i,round(1/i,3)))

Inverse of 1 is 1.0
Inverse of 2 is 0.5
Inverse of 3 is 0.333
Inverse of 4 is 0.25
Inverse of 5 is 0.2
Inverse of 6 is 0.167
Inverse of 7 is 0.143
Inverse of 8 is 0.125
Inverse of 9 is 0.111


In [69]:
dic1={'d':"delhi",'b':"banglore",'c':"chenni"}
dic1

{'d': 'delhi', 'b': 'banglore', 'c': 'chenni'}

In [90]:
res2=[]########converting dict to list 

In [91]:
for keys,values in dic1.items():
    res2.append(keys)
    res2.append(values)
print(res2)

['d', 'delhi', 'b', 'banglore', 'c', 'chenni']


In [92]:
list("chaitanya")###list comprehetion ##evry charactor separated out be an element.LIst function###list("arument")

['c', 'h', 'a', 'i', 't', 'a', 'n', 'y', 'a']

In [1]:
import numpy as np

In [96]:
arr=np.array([[1,2,3],[3,4,5]])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [98]:
arr1=np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
arr1=np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [102]:
arr1[:,0]

array([ 1,  6, 11, 16, 21])

In [103]:
arr1[0,:]

array([1, 2, 3, 4, 5])

In [104]:
arr1[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [105]:
arr1[2:,3:]

array([[14, 15],
       [19, 20],
       [24, 25]])

In [106]:
arr1[::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [109]:
arr1[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [121]:
arr1[::,1]

array([ 2,  7, 12, 17, 22])

In [123]:
arr2=np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
arr2.mean()

5.0

In [136]:
arr2.mean(0)

array([4., 5., 6.])

In [137]:
arr2.mean(1)

array([2., 5., 8.])

In [138]:
np.random.randint

<function RandomState.randint>

In [2]:
from numpy.random import randint

In [3]:
from numpy.random import randn

In [158]:
randn(5)

array([-0.0473328 , -0.28949875,  1.11901061, -1.8733548 ,  0.80393854])

In [178]:
randint(45)

43

In [180]:
arr3=np.arange(1,11).reshape(1,10)
arr3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [198]:
arr4=np.random.randint(1,8,7)
arr4

array([5, 4, 5, 5, 2, 5, 5])

In [199]:
arr4.max()

5

In [192]:
arr2.min()

1

In [204]:
arr4=np.random.randint(1,8,7)##### identifly the maximum value amoung those two arrays arr4,arr5
arr4

array([6, 5, 3, 1, 4, 3, 5])

In [196]:
arr5=np.random.randint(1,8,7)
arr5

array([4, 5, 6, 4, 5, 1, 1])

In [203]:
a=np.maximum(arr4,arr5)#### syntax
a

array([5, 5, 6, 5, 5, 5, 5])

In [205]:
np.nan

nan

In [207]:
arr0=np.array([[1,np.nan,np.nan],[np.nan,4,5]])
arr0

array([[ 1., nan, nan],
       [nan,  4.,  5.]])

In [208]:
type(arr0)

numpy.ndarray

In [210]:
ar1=np.array([[True,True,True],[False,False,False],[True,True,False]])
ar1

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [215]:
a=np.array([True,True,True])
a

array([ True,  True,  True])

In [216]:
a.all

<function ndarray.all>

In [217]:
a.any

<function ndarray.any>

In [ ]:
###########Where function ############

In [219]:
a=np.array([1,2,3,4])
b=np.array([100,200,300,400])
c=np.array([True,False,True,False])

In [221]:
a
b
c

array([ True, False,  True, False])

In [224]:
d=np.where(c,a,b)
print(d)

[  1 200   3 400]


In [226]:
e=np.array([[1,2],[3,4]])
f=np.array([[100,200],[300,400]])
g=np.array([[True,True],[False,False]])

In [228]:
h=np.where(g,e,f)
h

array([[  1,   2],
       [300, 400]])

In [ ]:
#################PANDAS###################

In [4]:
import pandas as pd

In [5]:
from pandas import Series

In [232]:
Ser1=Series([1,2,3,4,5,6])
Ser1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [236]:
Ser2=Series(["chenni","mumbai","bangalore"])
Ser2

0       chenni
1       mumbai
2    bangalore
dtype: object

In [237]:
Ser3=Series([100,200,300,400,500],index=['A','B','C','D','E'])### Series using list in this method
Ser3

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [241]:
Ser4=Series(np.arange(100,401,100),index=[30,40,50,50])###### Series using with arrays to genrate Series 
Ser4

30    100
40    200
50    300
50    400
dtype: int32

In [243]:
Ser5=Series({'A':'chaitanya','B':'Reddy','c':'palle'})
Ser5

A    chaitanya
B        Reddy
c        palle
dtype: object

In [244]:
Ser5.index

Index(['A', 'B', 'c'], dtype='object')

In [245]:
Ser5.values

array(['chaitanya', 'Reddy', 'palle'], dtype=object)

In [246]:
Ser5.items

<bound method Series.iteritems of A    chaitanya
B        Reddy
c        palle
dtype: object>

In [248]:
Ser6=Series(['alpha','beta','gamaa'],index=['A','A','B'])
Ser6

A    alpha
A     beta
B    gamaa
dtype: object

In [ ]:
#######selecting enteries in series #################

In [249]:
Ser3=Series([100,200,300,400,500],index=['A','B','C','D','E'])
Ser3

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [252]:
Ser3['A']## this method is called grab by index name,or grab by index label

100

In [253]:
Ser3[0]#### this method is called grab by default indexing method###########

100

In [254]:
Ser3[1:4]##  scliing This is called as grab by index Range###

B    200
C    300
D    400
dtype: int64

In [255]:
Ser3[["A","C"]]## this is called as grab by multiple index label.

A    100
C    300
dtype: int64

In [257]:
Ser3[Ser3 > 300]## this is called as grab by logic.......

D    400
E    500
dtype: int64

In [258]:
Ser3 > 300

A    False
B    False
C    False
D     True
E     True
dtype: bool

In [263]:
fb1=Series(np.array([5,2,5,1]),index=['vig1','vig2','san','shas'])
fb2=Series(np.array([np.nan,np.nan,5,3]),index=['vig1','vig2','san','shas'])

In [265]:
fb1

vig1    5
vig2    2
san     5
shas    1
dtype: int32

In [266]:
fb2

vig1    NaN
vig2    NaN
san     5.0
shas    3.0
dtype: float64

In [267]:
fb2.isnull()

vig1     True
vig2     True
san     False
shas    False
dtype: bool

In [268]:
fb2.notnull()

vig1    False
vig2    False
san      True
shas     True
dtype: bool

In [269]:
fb1+10

vig1    15
vig2    12
san     15
shas    11
dtype: int32

In [270]:
fb1+fb2

vig1     NaN
vig2     NaN
san     10.0
shas     4.0
dtype: float64

In [277]:
fb11=Series(np.where(fb2.isnull(),fb1,fb2),index=fb1.index)#### replacing null value using where method.
fb11

vig1    5.0
vig2    2.0
san     5.0
shas    3.0
dtype: float64

In [ ]:
#############Data Frames#################

In [6]:
from pandas import DataFrame

In [283]:
df1=DataFrame(np.arange(1,26).reshape(5,5))
df1

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [290]:
df1=DataFrame(np.arange(1,26).reshape(5,5),index=list('ABCDE'),columns=['col1','col2','col3','col4','col5'])
df1### renameing the columns labels index and row index labels

col1  col2  col3  col4  col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15
D    16    17    18    19    20
E    21    22    23    24    25

In [292]:
df2=DataFrame({"Name":['chaitanya','vig1','vig2','giji1','adithya'],"Age":[25,25,30,24,26]})
df2

Name  Age
0  chaitanya   25
1       vig1   25
2       vig2   30
3      giji1   24
4    adithya   26

In [295]:
df2=DataFrame({"Name":['chaitanya','vig1','vig2','giji1','adithya'],"Age":[25,25,30,24,26]},index=list('ABCDE'))
df2

Name  Age
A  chaitanya   25
B       vig1   25
C       vig2   30
D      giji1   24
E    adithya   26

In [7]:
df3=DataFrame({"compay":["TCS","WIPRO","GOOGLE","YAHOO","CISCO"],"Ticker":["TCS","WIP","GOOG","YAH","CISC"],
               "price":[100,200,250,310,280]})
df3

compay Ticker  price
0     TCS    TCS    100
1   WIPRO    WIP    200
2  GOOGLE   GOOG    250
3   YAHOO    YAH    310
4   CISCO   CISC    280

In [8]:
df3['compay']#### singel coloumn it will give series 

0       TCS
1     WIPRO
2    GOOGLE
3     YAHOO
4     CISCO
Name: compay, dtype: object

In [9]:
df3[['compay','price']]## grabing mutilple columns we will get data frame 

compay  price
0     TCS    100
1   WIPRO    200
2  GOOGLE    250
3   YAHOO    310
4   CISCO    280

In [14]:
df3[df3['price']>200]#### grab by logic fetching data

compay Ticker  price
2  GOOGLE   GOOG    250
3   YAHOO    YAH    310
4   CISCO   CISC    280

In [17]:
df3['price']>200

0    False
1    False
2     True
3     True
4     True
Name: price, dtype: bool

In [18]:
df3[0:3]#grab by using index range

compay Ticker  price
0     TCS    TCS    100
1   WIPRO    WIP    200
2  GOOGLE   GOOG    250

In [21]:
df3['Year']=[2020,2019,2018,2017,2016]##### adding new columns to the data frame using list method
df3

compay Ticker  price  Year
0     TCS    TCS    100  2020
1   WIPRO    WIP    200  2019
2  GOOGLE   GOOG    250  2018
3   YAHOO    YAH    310  2017
4   CISCO   CISC    280  2016

In [23]:
df3['Series']=np.array([200,3000,3000,4000,5000])#### adding new column using array method...
df3

compay Ticker  price  Year  Series
0     TCS    TCS    100  2020     200
1   WIPRO    WIP    200  2019    3000
2  GOOGLE   GOOG    250  2018    3000
3   YAHOO    YAH    310  2017    4000
4   CISCO   CISC    280  2016    5000

In [9]:
df3['discountedprice']=df3['price']*0.9#### 10 percentage of discount price############
df3

compay Ticker  price  discountedprice
0     TCS    TCS    100             90.0
1   WIPRO    WIP    200            180.0
2  GOOGLE   GOOG    250            225.0
3   YAHOO    YAH    310            279.0
4   CISCO   CISC    280            252.0

In [16]:
df3['Year']=[2001,2002,2003,2004,2005]
df3

compay Ticker  price  discountedprice  Year
0     TCS    TCS    100             90.0  2001
1   WIPRO    WIP    200            180.0  2002
2  GOOGLE   GOOG    250            225.0  2003
3   YAHOO    YAH    310            279.0  2004
4   CISCO   CISC    280            252.0  2005

In [19]:
del df3['Year'] ## deleting the colummn in the data set 
df3

compay Ticker  price  discountedprice
0     TCS    TCS    100             90.0
1   WIPRO    WIP    200            180.0
2  GOOGLE   GOOG    250            225.0
3   YAHOO    YAH    310            279.0
4   CISCO   CISC    280            252.0

In [22]:
df3.index

RangeIndex(start=0, stop=5, step=1)

In [23]:
df3.columns

Index(['compay', 'Ticker', 'price', 'discountedprice'], dtype='object')

In [24]:
df3.values

array([['TCS', 'TCS', 100, 90.0],
       ['WIPRO', 'WIP', 200, 180.0],
       ['GOOGLE', 'GOOG', 250, 225.0],
       ['YAHOO', 'YAH', 310, 279.0],
       ['CISCO', 'CISC', 280, 252.0]], dtype=object)

In [27]:
df3['price'].values

array([100, 200, 250, 310, 280], dtype=int64)

In [33]:
df3.ix[0]

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


compay             TCS
Ticker             TCS
price              100
discountedprice     90
Name: 0, dtype: object

In [33]:
df4=DataFrame(np.arange(1,26).reshape(5,5),index=[1,2,3,4,5],columns=list('ABCDE'))
df4

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [32]:
df4.ix[0]

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A    1
B    2
C    3
D    4
E    5
Name: t, dtype: int32

In [11]:
df4.iloc[0]

A    1
B    2
C    3
D    4
E    5
Name: 1, dtype: int32

In [12]:
df4.iloc[0,0]

1

In [37]:
df4.iloc[:,0]### posotional feteching 

t     1
u     6
v    11
x    16
y    21
Name: A, dtype: int32

In [13]:
df4.iloc[3:,0:]

A   B   C   D   E
4  16  17  18  19  20
5  21  22  23  24  25

In [14]:
df4

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [15]:
df4.iloc[2:4,1:4]

B   C   D
3  12  13  14
4  17  18  19

In [ ]:
####loc will be lables...

In [51]:
df4.loc[:,'B']

t     2
u     7
v    12
x    17
y    22
Name: B, dtype: int32

In [59]:
df4.loc[:,['B','D']]

B   D
t   2   4
u   7   9
v  12  14
x  17  19
y  22  24

In [60]:
df4.loc[:,['B','C','D']]

B   C   D
t   2   3   4
u   7   8   9
v  12  13  14
x  17  18  19
y  22  23  24

In [17]:
df4

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [19]:
df4.loc[1:3,['A','B']]

A   B
1   1   2
2   6   7
3  11  12

In [25]:
df4.loc[1:6,['A','B','D']]

A   B   D
1   1   2   4
2   6   7   9
3  11  12  14
4  16  17  19
5  21  22  24

In [26]:
df4.iloc[1:4,2:3]

C
2   8
3  13
4  18

In [29]:
df4.drop(1)

A   B   C   D   E
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [30]:
del df4['A']

In [31]:
df4

B   C   D   E
1   2   3   4   5
2   7   8   9  10
3  12  13  14  15
4  17  18  19  20
5  22  23  24  25

In [34]:
df4

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [35]:
df4.drop(2)

A   B   C   D   E
1   1   2   3   4   5
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [36]:
df4

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [39]:
df4.drop('A',axis=1)
df4

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [42]:
df4.drop('A',axis=1,inplace=True)####### using inplace real chagnges in the data set.......


KeyError: "['A'] not found in axis"